server:
  port: 8040
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    consumer-movie: /movie/**
    provider-user:
      path: /users/**
      sensitive-headers:
#ribbon:
#  eureka:
#    enabled: false
provider-user:
  ribbon:
    listOfServers: http://192.168.56.1:8001,http://192.168.56.1:8000