server:
  port: 8031
spring:
  application:
    name: hystrix-turbine
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#turbine:
#  appConfig: consumer-movie
#  clusterNameExpression: "'default'"